USE CarpoolingTEC;



INSERT INTO Categorias(NOMBRE, PUNTOSPORVIAJE, VMAXIMOSCATEGORIA, VMINIMOSCATEGORIA)
VALUES('AMATEUR',10, 0, 15); 

INSERT INTO Categorias(NOMBRE, PUNTOSPORVIAJE, VMAXIMOSCATEGORIA, VMINIMOSCATEGORIA)
VALUES('BRONCE',20, 16, 30); 

INSERT INTO Categorias(NOMBRE, PUNTOSPORVIAJE, VMAXIMOSCATEGORIA, VMINIMOSCATEGORIA)
VALUES('PLATA',30, 31, 45); 

INSERT INTO Categorias(NOMBRE, PUNTOSPORVIAJE, VMAXIMOSCATEGORIA, VMINIMOSCATEGORIA)
VALUES('ORO',40, 46, 60);

-- SELECT * FROM Categorias;




INSERT INTO Fechas(DIA, MES, ANO)
VALUES(28,05,2019);

INSERT INTO Fechas(DIA, MES, ANO)
VALUES(06,06,2019);

INSERT INTO Fechas(DIA, MES, ANO)
VALUES(12,06,2019);

-- SELECT * FROM Fechas;




INSERT INTO Parqueos(NUMEROPARQUEO, ACTIVO)
VALUES('A-01', TRUE); 

INSERT INTO Parqueos(NUMEROPARQUEO, ACTIVO)
VALUES('B-08', FALSE); 

INSERT INTO Parqueos(NUMEROPARQUEO, ACTIVO)
VALUES('C-05', TRUE); 

INSERT INTO Parqueos(NUMEROPARQUEO, ACTIVO)
VALUES('B-02', FALSE); 

INSERT INTO Parqueos(NUMEROPARQUEO, ACTIVO)
VALUES('A-02', TRUE); 

-- SELECT * FROM Parqueos;




INSERT INTO Productos(NOMBRE, COSTO)
VALUES('GORRA TEC',5000);

INSERT INTO Productos(NOMBRE, COSTO)
VALUES('SOMBRILLA TEC',2500);

INSERT INTO Productos(NOMBRE, COSTO)
VALUES('VASO TEC',3000);

-- SELECT * FROM Productos;



INSERT INTO Pasajeros(CEDULA, CARNET, NOMBRE, APELLIDO, CORREO, IdCategoria, PUNTOS, CONTRASENA, ACTIVO)
VALUES(604410064, 2016081117,'Hernaldo','Ramirez','nano_12_rm@gmail.com',2,100,'Nano123', TRUE); 

INSERT INTO Pasajeros(CEDULA, CARNET, NOMBRE, APELLIDO, CORREO, IdCategoria, PUNTOS, CONTRASENA, ACTIVO)
VALUES(204560876, 2016243863,'Gerardo','Zeledon','mecace@gmail.com',1,50,'Gato123', TRUE); 

INSERT INTO Pasajeros(CEDULA, CARNET, NOMBRE, APELLIDO, CORREO, IdCategoria, PUNTOS, CONTRASENA, ACTIVO)
VALUES(607430723, 2016167796,'Juan','Esquivel','juanesro@gmail.com',4,250,'Gatito123', TRUE); 

INSERT INTO Pasajeros(CEDULA, CARNET, NOMBRE, APELLIDO, CORREO, IdCategoria, PUNTOS, CONTRASENA, ACTIVO)
VALUES(605470765, 2016048367,'Crisptofer','Fernandez','crisfer@gmail.com',3,185,'Perro123', TRUE); 

INSERT INTO Pasajeros(CEDULA, CARNET, NOMBRE, APELLIDO, CORREO, IdCategoria, PUNTOS, CONTRASENA, ACTIVO)
VALUES(503650826, 200955696,'Mario','Molina','marmol@gmail.com',4,40,'Elcrack12', FALSE); 
-- SELECT * FROM Pasajero;


INSERT INTO Amigos(IdEmisor, IdReceptor, AMIGO)
VALUES(1,2,TRUE);

INSERT INTO Amigos(IdEmisor, IdReceptor, AMIGO)
VALUES(1,3,TRUE);

INSERT INTO Amigos(IdEmisor, IdReceptor, AMIGO)
VALUES(1,4,FALSE);

INSERT INTO Amigos(IdEmisor, IdReceptor, AMIGO)
VALUES(3,1,FALSE);

INSERT INTO Amigos(IdEmisor, IdReceptor, AMIGO)
VALUES(3,2,TRUE);

-- SELECT * FROM Amigos;



INSERT INTO Administradors(IdPasajero)
VALUES(1); 

INSERT INTO Administradors(IdPasajero)
VALUES(3); 

-- SELECT * FROM Administradors;




INSERT INTO Chofers(IdPasajerof)
VALUES(1); 

INSERT INTO Chofers(IdPasajerof)
VALUES(3); 

INSERT INTO Chofers(IdPasajerof)
VALUES(2); 

-- SELECT * FROM Chofers;


INSERT INTO Autos(PLACA, MARCA, MODELO, CAPACIDAD, IdChofer)
VALUES('BCM-087','TOYOTA','FORTUNER',7, 1); 

INSERT INTO Autos(PLACA, MARCA, MODELO, CAPACIDAD, IdChofer)
VALUES('BFF-068','NISSAN','FRONTIER',5, 2); 

INSERT INTO Autos(PLACA, MARCA, MODELO, CAPACIDAD, IdChofer)
VALUES('BSH-465','ISUZU','D-MAX',5, 3); 

-- SELECT * FROM Autos;


INSERT INTO Compras(IdPasajeroFC, IdProductoFC, DETALLE, IdFechaFC)
VALUES(3,2, 'Compra de producto en X-ASETEC', 1); 

INSERT INTO Compras(IdPasajeroFC, IdProductoFC, DETALLE, IdFechaFC)
VALUES(1,1,'Compra en X-Toño Carrito', 2); 

INSERT INTO Compras(IdPasajeroFC, IdProductoFC, DETALLE, IdFechaFC)
VALUES(3,3,'Compra en X-ASETEC', 2); 

-- SELECT * FROM Compras;




INSERT INTO Viajes(IdChoferFV, IdAutoFV, IdParqueoFV, ACTIVO, MES)
VALUES(1, 3, 2, TRUE, 0); 

INSERT INTO Viajes(IdChoferFV, IdAutoFV, IdParqueoFV, ACTIVO, MES)
VALUES(2, 2, 4, FALSE, 1); 

INSERT INTO Viajes(IdChoferFV, IdAutoFV, IdParqueoFV, ACTIVO, MES)
VALUES(1, 3, 3, FALSE, 0); 

-- SELECT * FROM Viajes;




INSERT INTO ParticipanteViajes(IdPasajeroFP, IdViajeFP, CODIGOVIAJE)
VALUES(1,1, 'CDMX12'); 

INSERT INTO ParticipanteViajes(IdPasajeroFP, IdViajeFP, CODIGOVIAJE)
VALUES(2,1, 'CDMX12-1'); 

INSERT INTO ParticipanteViajes(IdPasajeroFP, IdViajeFP, CODIGOVIAJE)
VALUES(4,1, 'CDMX12-2'); 

INSERT INTO ParticipanteViajes(IdPasajeroFP, IdViajeFP, CODIGOVIAJE)
VALUES(4,3, 'CDMX12-3'); 

INSERT INTO ParticipanteViajes(IdPasajeroFP, IdViajeFP, CODIGOVIAJE)
VALUES(4,2, 'frsdgfvsd-5'); 

INSERT INTO ParticipanteViajes(IdPasajeroFP, IdViajeFP, CODIGOVIAJE)
VALUES(3,2, 'CPC02'); 

INSERT INTO ParticipanteViajes(IdPasajeroFP, IdViajeFP, CODIGOVIAJE)
VALUES(2,2, 'CPC02-1'); 

INSERT INTO ParticipanteViajes(IdPasajeroFP, IdViajeFP, CODIGOVIAJE)
VALUES(4,2, 'CPC02-2'); 

-- SELECT * FROM ParticipanteViajes;


INSERT INTO Validaciones(Carnet)
VALUES(2016081117); 

INSERT INTO Validaciones(Carnet)
VALUES(2016243863); 

INSERT INTO Validaciones(Carnet)
VALUES(2016167796); 

INSERT INTO Validaciones(Carnet)
VALUES(2016048367); 

INSERT INTO Validaciones(Carnet)
VALUES(200955696); 

-- SELECT * FROM Validaciones;

-- CALL sp_vmes(1,0);
