CREATE PROCEDURE `sp_buscar` (IN Param VARCHAR(50))
BEGIN
SELECT IdPasajero, NOMBRE, APELLIDO, CORREO
FROM Pasajeros 
WHERE NOMBRE = Param OR APELLIDO = Param OR NOMBRE LIKE CONCAT('%', Param, '%') OR APELLIDO LIKE CONCAT('%', Param, '%');
END